### ISSUE TITLE
If message payload is empty, msgHandler is not called

### ISSUE THREAD

**Issue by enthus1ast** [benumbed/nim-amqp#3]
When the payload is empty the msgHandler is not called,
so there is no way to ack manualy and RabbitMQ reports them as "Unacked".

The output thats generated is (for each message):

```
DBG 2020-09-19 22:25:10.470+02:00 Content Header                             tid=13830 classId=60 weight=0 bodySize=0 propFlags=12288
DBG 2020-09-19 22:25:10.470+02:00 basic.deliver                              tid=13830 consumerTag=amq.ctag-2XyR-_2D_Jv73iYKzOCH9w deliveryTag=8 redelivered=true exchangeName= routingKey=youtube_song
```
i basically use your example consumer (with my logic added in the handler), if you need more information please say so.
(could be that i've missed something :) )

**Comment by benumbed** [comment]
Ok I can repro this using the `isMainModule` demo code and a blank message body, I'll look into it.

**Comment by benumbed** [comment]
Okay so it's because the AMQP server doesn't send a 'content body' header if the message is blank (aka it just doesn't send blank messages).  For now, to work around this, if you have control of the producer, you can add some throwaway value into the body, and the message handler will trigger (since the server will send the proper header and message content).

I'm not 100% sure how I want to solve for this atm, I'll need to think about it today.

**Comment by enthus1ast** [comment]
i must admit i do not know much about the AMQP protocol (just what i've learned reading your code actually), but for me it would be most logically to just deliver the empty content. Maybe a look how one of the official rabbitmq clients handles this case, could be inspiring.

**Comment by enthus1ast** [comment]
just checked with the python Pika client, it deliveres the empty message.
